name: hackernews
description: A new Flutter project for fetching news articles from hacker news website API.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2 
  device_preview: ^0.5.5
  dio: ^3.0.10
  flutter_html: ^1.2.0
  get: ^3.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
